# LavaCrates Konfiguráció
# Használj HEX kódokat: &#RRGGBB (pl. &#FF5555)
# Hologram sorváltás: |

crates:
  alap:
    location:
      world: world
      x: 0
      y: 64
      z: 0
    key_item:
      ==: org.bukkit.inventory.ItemStack
      v: 3465
      type: TRIPWIRE_HOOK
      meta:
        ==: ItemMeta
        display-name: '{"text":"","extra":[{"text":"Láda Kulcs","color":"gold","italic":false}]}'
    items: [] # Ide kerülnek a mentett tárgyak az esélyekkel
    hologram:
      - "&#FF8C00&lALAP LÁDA"
      - "&7[Bal klikk: Előnézet]"
      - "&#FFD700Jobb klikk a nyitáshoz!"

# Ha új ládát hozol létre a /lc create paranccsal, 
# az automatikusan meg fog jelenni itt a fájlban is.
