# A hologrammoknál a '|' karakter jelöli az új sort.

# Alap példák, ezenkívül is tudsz csinálni más ládákat!
crates:
  alap:
    location:
    key_item:
    items: []
    hologram:
      - "&#FF8C00&lALAP LÁDA"
      - "&7Kattints a nyitáshoz!"
      - "&#FFD700Kulcs szükséges"
    messages:
      chat: "&#FF8C00LavaCrates &8» &fGratulálunk &e%player%&f! Nyertél egy &6%item%&f-et!"
      title: "&#FFD700&lGRATULÁLUNK!"
      subtitle: "&fJutalmad: &e%item%"

  legendas:
    location:
    key_item:
    items: []
    hologram:
      - "&#B22222&lLEGENDÁS LÁDA"
      - "&7Ritka jutalmak várakoznak..."
      - "&#FF4500| NAGYON RITKA |"
    messages:
      chat: "&#B22222LavaCrates &8» &#FF4500%player% &#fkinyitotta a &#B22222Legendás Ládát &#fés nyert: &#FF4500%item%&f!"
      title: "&#B22222&lLEGENDÁS NYEREMÉNY!"
      subtitle: "&fEzt jól elkaptad: &e%item%"
