# ==========================================
#          LavaCrates Konfiguráció
# ==========================================

# Üzenetek beállítása
messages:
  no-permission: "&#FF5555Nincs jogod ehhez a parancshoz!"
  reload: "&#FF8C00LavaCrates &8» &#00FF7FPlugin sikeresen újratöltve!"
  crate-created: "&#FF8C00LavaCrates &8» &#00FF7FLáda létrehozva: &#FFD700%crate%"
  item-added: "&#FF8C00LavaCrates &8» &#00FF7FTárgy sikeresen hozzáadva a ládához!"
  key-needed: "&#FF5555Ehhez a ládához kulcsra van szükséged!"
  givekey-success: "&#FF8C00LavaCrates &8» &#00FF7FSikeresen adtál &#FFD700%amount%x &#00FF7Fkulcsot neki: &#FFD700%player%"

# GUI-k címei
gui-titles:
  preview: "&#FF8C00%crate% &8- &#000000Tartalom"
  opening: "&#FF8C00Nyitás: &#000000%crate%"

# Tárgyak leírása a Preview-ban
lore:
  separator: "&#778899&m----------------"
  chance: "&#B0C4DEEsély: &#FFD700%chance%%"

# Ládaparti Rendszer
# Itt minden ládához külön szekciót hozhatsz létre.
# A szekció neve (pl. 'alap') egyezzen meg a láda nevével!
party:
  alap:
    threshold: 50
    current: 0
    commands:
      - "lc keyall alap 1 v"
      - "broadcast &#FF8C00LavaCrates &8» &#00FF7FAz Alap ládaparti elérve! Mindenki kapott egy virtuális kulcsot!"
      - "playsound entity.firework_rocket.blast ambient @a"
  legendas:
    threshold: 100
    current: 0
    commands:
      - "give @a diamond 10"
      - "broadcast &#FF8C00LavaCrates &8» &#FFD700HATALMAS LEGENDA PARTI! Mindenki kapott 10 gyémántot!"
      - "playsound entity.ender_dragon.growl ambient @a"

# Frissítési gyakoriság (tickben) - 20 tick = 1 másodperc
hologram-update-interval: 20
